export const GET_INFLUENCERS = "GET_INFLUENCERS";
export const GET_INFLUENCER_DETAILS = "GET_INFLUENCER_DETAILS";
export const GET_ERRORS = "GET_ERRORS";

export const GET_PROFILE_DETAILS = "GET_PROFILE_DETAILS";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";